apiVersion: v1
kind: ConfigMap
metadata:
  name: golf-app-configmap
data:
  PG_SERVER: golf-db-0.golf-db-service
  spring.datasource.url: jdbc:postgresql://${PG_SERVER}/golf
  spring.profiles.active: prod