apiVersion: v1
kind: PersistentVolume
metadata:
  name: golf-volume
spec:
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 512M
  hostPath:
    path: /var/golfdb