apiVersion: v1
kind: PersistentVolume
metadata:
  name: golf-web-volume
spec:
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2M
  hostPath:
    path: /cert
