kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: golf-backup-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: do-block-storage