apiVersion: v1
kind: PersistentVolume
metadata:
  name: golf-volume
spec:
  storageClassName: do-block-storage
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /var/golfdb