apiVersion: v1
kind: Secret
metadata:
  name: golf-app-secret
type: Opaque
data:
  mail-username: {{ .Values.golfApp.mailUsername }}
  mail-password: {{ .Values.golfApp.mailPassword }}
  recaptcha-site: {{ .Values.golfApp.recaptchaSite }}
  recaptcha-secret: {{ .Values.golfApp.recaptchaSecret }}
  allowed-origins: {{ .Values.golfApp.allowedOrigins }}
  facebook-secret: {{ .Values.golfApp.facebookSecret }}
  google-secret: {{ .Values.golfApp.googleSecret }}
