apiVersion: v1
kind: Secret
metadata:
  name: golf-db-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.golfDb.credentials.username }}
  POSTGRES_PASSWORD: {{ .Values.golfDb.credentials.password }}