apiVersion: v1
kind: Secret
metadata:
  name: golf-db-secret
type: Opaque
data:
  golf-db-username: {{ .Values.golfDb.credentials.username }}
  golf-db-password: {{ .Values.golfDb.credentials.password }}