apiVersion: v1
kind: Secret
metadata:
  name: golf-app-secret
type: Opaque
data:
  spring.mail.username: {{ .Values.golfApp.mailUsername }}
  spring.mail.password: {{ .Values.golfApp.mailPassword }}
  google.recaptcha.key.site: {{ .Values.golfApp.recaptchaSite }}
  google.recaptcha.key.secre: {{ .Values.golfApp.recaptchaSecret }}
  cors.allowedOrigins: {{ .Values.golfApp.allowedOrigins }}
  pring.security.oauth2.client.registration.facebook.client-secret: {{ .Values.golfApp.facebookSecret }}
  spring.security.oauth2.client.registration.google.client-secret: {{ .Values.golfApp.googleSecret }}
  player.emailPwd: {{ .Values.golfApp.emailPwd }}
  spring.datasource.username: {{ .Values.golfDb.credentials.username }}
  spring.datasource.password: {{ .Values.golfDb.credentials.password }}
