apiVersion: batch/v1
kind: CronJob
metadata:
  name: golf-backup
spec:
  # Backup the database every day at 2AM
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: golf-backup
            image: postgres:13
            command: ["/bin/sh"]
            args: ["-c", 'echo "$PGPASS" > /root/.pgpass && chmod 600 /root/.pgpass && pg_dump -w -U golf_usr -h golf-db-service golf --clean > /backups/backup-$(date +"%m-%d-%Y-%H-%M").sql']
            env:
            - name: PGPASS
              valueFrom:
                secretKeyRef:
                  name: golf-backup-secret
                  key: pgpass
            volumeMounts:
            - mountPath: "/backups"
              name: backup-storage
          restartPolicy: Never
          volumes:
          - name: backup-storage
            persistentVolumeClaim:
              claimName:  golf-backup-pvc