{{- if eq .Values.development true }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: golf-db-pv
spec:
  storageClassName: golf-db-pv
  capacity:
    storage: 200M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
    type: Directory
{{- end }}