apiVersion:  v1
kind: PersistentVolume
metadata:
  name: golf-backup-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: backup-storage
  volumeMode: Filesystem
  capacity:
    storage: 10M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /C/Data/backup
    type: Directory