apiVersion:  v1
kind: PersistentVolume
metadata:
  name: golf-web-pv
spec:
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  volumeMode: Filesystem
  capacity:
    storage: 1M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /C/Data/cert
    type: DirectoryOrCreate